### ISSUE TITLE
Update 0.3.9 - Android App can't load data

### ISSUE THREAD

**Issue by Oberlurch3000** [te-online/timemanager#148]
Since the latest update 0.3.9 the android app isn't loading any data.
I tried to reinstall the app and reboot the clouds server.

Am I the only one having this issue or could this be caused by the update?

**Comment by te-online** [comment]
It could very well be caused by the update! Thanks for reporting. I’m not using the Android app and therefore not testing it before release 😬 do you have anything in your nextcloud logs?

On 5 Dec 2023, at 07.55, Oberlurch3000 ***@***.***> wrote:

﻿

Since the latest update 0.3.9 the android app isn't loading any data.
I tried to reinstall the app and reboot the clouds server.

Am I the only one having this issue or could this be caused by the update?

**Comment by Oberlurch3000** [comment]
Unfortunately there are no information in the logs (even in debug mode).

**Comment by te-online** [comment]
I can see this error in my log when I call the API that the app uses:

```
[core] Error: Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle. at <<closure>>

 0. /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php line 293
    OC\DB\QueryBuilder\QueryBuilder->execute()
 1. /var/www/html/lib/public/AppFramework/Db/QBMapper.php line 336
    OC\DB\QueryBuilder\QueryBuilder->executeQuery()
 2. /var/www/html/custom_apps/timemanager/lib/Db/ObjectMapper.php line 334
    OCP\AppFramework\Db\QBMapper->findEntities(["OC\\DB\\QueryBuilder\\QueryBuilder"])
 3. /var/www/html/custom_apps/timemanager/lib/Db/ObjectMapper.php line 322
    OCA\TimeManager\Db\ObjectMapper->getCreatedObjectsAfterCommit(["OC\\DB\\QueryBuilder\\QueryBuilder"])
 4. /var/www/html/custom_apps/timemanager/lib/Db/StorageHelper.php line 218
    OCA\TimeManager\Db\ObjectMapper->getObjectsAfterCommit("*** sensitive parameters replaced ***")
 5. /var/www/html/custom_apps/timemanager/lib/Controller/TApiController.php line 204
    OCA\TimeManager\Db\StorageHelper->getObjectsAfterCommit("clients", "*** sensitive parameters replaced ***")
 6. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\TimeManager\Controller\TApiController->updateObjects("*** sensitive parameters replaced ***")
 7. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\TimeManag ... "], "updateObjects")
 8. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\TimeManag ... "], "updateObjects")
 9. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OCA\\TimeManage ... r", "updateObjects", ["OC\\AppFramewo ... "], ["timemanager.t_api.updateObjects"])
10. /var/www/html/lib/base.php line 1062
    OC\Route\Router->match("/apps/timemanager/api/updateObjects")
11. /var/www/html/index.php line 36
    OC::handleRequest()

POST /index.php/apps/timemanager/api/updateObjects
```

Maybe you have the same message in your log? I'm not using Oracle, so I'm not sure why it's limited, but that seems to be the reason the response only contains empty arrays for all entities.

I will look into this as soon as I can and am sorry that the Android app is not working currently.

**Comment by cepela** [comment]
Hallo, I am facing the same issue.

**Comment by te-online** [comment]
Yes, thank you all for reporting 😊 

I'm pretty sure it's related to the 1000 expressions limit in the query. As soon as you have made more than 1000 changes to your database, you will run into this issue and the response from the API will be empty. In that case the Android app seems to display nothing.

I can probably fix this by making multiple queries, but that may slow down the endpoint, depending on the size of your database. 

The more sustainable solution will be to re-design the sync API and create a new mobile client (as the Android app's development has been discontinued).

Will update here, when the mentioned fix is available – give it a few days.

**Comment by te-online** [comment]
This should be fixed in 0.3.10 – sorry about this!

Please re-open if you see this happen again 😊

**Comment by Oberlurch3000** [comment]
Hello,
for me the problem still exists. The app now loads the costumer but no data like tasks or times I've tracked before. It's not possible to make new entries.

**Comment by cepela** [comment]
I am OK.

**Comment by Oberlurch3000** [comment]
Unfortunatly there's nothing in the logs.

**Comment by te-online** [comment]
@Oberlurch3000 Can you confirm that you are using version `0.3.10`? 😊 

When I query the endpoint, that the Android app uses, on my own Nextcloud, it returns all clients, projects, tasks and times. And my database holds quite a few more than a 1000 commits. 

Maybe if you post some details of your server (Operating system, database type and version), I can reproduce your issue.

Beware that shared clients do not display in the Android app, as the sharing feature was introduced before the Android app and the API it's using were discontinued.

**Comment by Oberlurch3000** [comment]
Yes, I'm running 0.3.10. Also confirmed via occ command.
I found that my log level in NC config was set to 2 so I didn't get any info or debug logs.
Now I get the following output if I try to use the android app:
```
[timemanager] Information: API Request with commit: 

POST //index.php/apps/timemanager/api/updateObjects
from **** by **** at 2023-12-11T19:33:16+00:00
```
and
```
[timemanager] Information: Sending response [omitted] and commit c33a1061-ff52-44ea-bccd-b954d3ba37b3

POST //index.php/apps/timemanager/api/updateObjects
from **** by **** at 2023-12-11T19:33:16+00:00
```

**Comment by te-online** [comment]
The debug logs look fine to me 😊 And it seems like you're using MariaDb, so no issue there.

I wouldn't think that the failed downgrade and later upgrade would have caused this. But are you sure you are running `0.3.10` now? And can you see all your clients, projects etc. in Nextcloud?

Maybe it would be easiest to remove the app and do a clean install. **Make sure to have a database backup, as this is where your data is stored.**

**Comment by te-online** [comment]
@Oberlurch3000 Would you mind sharing your PHP version? Maybe you're running into this issue: !149

**Comment by Oberlurch3000** [comment]
I'm on PHP 8.1.17.
It looks like completly removing the app and reinstalling didn't solve the problem.

**Comment by te-online** [comment]
Okay! I can see that whatever client you're using (presumably the Android app made by @joleaf), is sending a commit that it last stored. It will only get the "creates" and "updates" _after_ this given commit. I can see your server's response didn't include any projects, for instance. But there must be projects in your database, if you have tasks and time entries. 

Hence, if your data is consistent on the server and visible in Nextcloud, it may have been corrupted in the store of your Android app. Is there a way for you to reset its local database, if there is such thing? Then it should send an initial request for _all_ data without a commit and that would result in your server sending over _all_ of the data. This could have been the issue with the problematic `0.3.9` version where this response would have been empty, so maybe your Android app missed some objects, but now thinks it's in-sync. Now that this response got fixed in `0.3.10`, you should be able to do the initial, as well as subsequent syncs without inconsistencies 🙏 

_PS: I removed the JSON from your post as you may not want this to be public 😊_

**Comment by Oberlurch3000** [comment]
@te-online:
You are right about the app by @joleaf.
The database should be ok because I've no problems to use the web based version.
I uninstalled the android app and tried to delete all app data and the apps cache. No changes.
I also entered a new costumer with project and tasks via web interface and in the android app.
Both new costumers show up in the app and I can add times etc...
But the existing costumer doesn't show up and the app still isn't showing any data on the dashboard tab.

This is how it looks like with just the existing project in the database:
![Screenshot_20231213-072117](https://github.com/te-online/timemanager/assets/44377287/48931e57-5d21-42cd-a23d-da39eabca6d1)
![Screenshot_20231213-072128](https://github.com/te-online/timemanager/assets/44377287/04a69bbc-5c61-49ac-b6d6-f683beb53a8e)

**Comment by te-online** [comment]
@Oberlurch3000 Update! I believe I found the root cause of your issue. The group share feature included a bigger refactor of the ObjectMapper and here we have introduced a regression. I'm sorry this massive bug slipped through my review.

I will release a fixed version as soon as possible.

**Comment by te-online** [comment]
@Oberlurch3000 Please check out release 0.3.11, it should hopefully fix the remaining issues you're facing.

**Comment by Oberlurch3000** [comment]
Yeah! Problem solved! Thank you ;)
